import { AppSidebar } from "@/app/_widgets/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/sidebar";

import { Toaster } from "@/components/sonner";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactQueryProvider } from "./_providers/query";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="p-6">
              <SidebarTrigger className="mb-6" />
              {children}
            </main>
          </SidebarProvider>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
